"""Demo mode sample data fixtures.

Used when JIRA_TOKEN is not configured. Provides representative BigRock,
Feature, and RFE data so the frontend can be developed and demonstrated
without Jira access.
"""

from __future__ import annotations

from datetime import datetime, timezone

from release_planner.api_models import (
    CandidateResponse,
    FeatureRow,
    FilterOptions,
    PillarSummary,
    RfeRow,
    RockSummary,
    SummaryStats,
)
from release_planner.constants import JIRA_BROWSE_URL

_SAMPLE_BIG_ROCKS: list[RockSummary] = [
    RockSummary(
        priority=1,
        name="MaaS",
        full_name="MaaS (continue from 3.4)",
        pillar="Inference",
        state="continue from 3.4",
        owner="Pat Johnson",
        outcome_keys=["RHAISTRAT-9001"],
        outcome_descriptions={"RHAISTRAT-9001": "Model as a Service enablement"},
        feature_count=5,
        rfe_count=2,
        notes="",
    ),
    RockSummary(
        priority=2,
        name="Gen AI Studio",
        full_name="Gen AI Studio / Prompt Lab (continue from 3.4)",
        pillar="Agents",
        state="continue from 3.4",
        owner="Morgan Lee",
        outcome_keys=["RHAISTRAT-9002"],
        outcome_descriptions={"RHAISTRAT-9002": "GenAI Studio for enterprise AI workflows"},
        feature_count=4,
        rfe_count=1,
        notes="",
    ),
    RockSummary(
        priority=5,
        name="llm-d / xKS",
        full_name="Llm-d / llm-d on xKS (continue from 3.4)",
        pillar="Inference",
        state="continue from 3.4",
        owner="Alex Rivera",
        outcome_keys=["RHAISTRAT-9003"],
        outcome_descriptions={"RHAISTRAT-9003": "llm-d inference gateway"},
        feature_count=3,
        rfe_count=1,
        notes="",
    ),
    RockSummary(
        priority=7,
        name="Eval Hub",
        full_name="Eval Hub (continue from 3.4)",
        pillar="Data",
        state="continue from 3.4",
        owner="Jordan Taylor",
        outcome_keys=["RHAISTRAT-9006"],
        outcome_descriptions={"RHAISTRAT-9006": "Model evaluation hub"},
        feature_count=3,
        rfe_count=2,
        notes="",
    ),
    RockSummary(
        priority=8,
        name="AI Hub incl MCP",
        full_name="AI Hub including MCP catalog & registry (continue from 3.4)",
        pillar="Platform",
        state="continue from 3.4",
        owner="Casey Martin",
        outcome_keys=["RHAISTRAT-9007"],
        outcome_descriptions={"RHAISTRAT-9007": "AI Hub and MCP catalog"},
        feature_count=4,
        rfe_count=2,
        notes="",
    ),
]

_SAMPLE_FEATURES: list[FeatureRow] = [
    FeatureRow(
        big_rock="MaaS",
        issue_key="RHAISTRAT-1520",
        status="In Progress",
        priority="Major",
        phase="EA1",
        summary="Support vLLM multi-node inference",
        components="Serving",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Jane Doe",
        delivery_owner="John Smith",
        rfe="RHAIRFE-456",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="MaaS",
        issue_key="RHAISTRAT-1521",
        status="Refinement",
        priority="Critical",
        phase="EA2",
        summary="Auto-scaling for model endpoints",
        components="Serving, Platform",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Jane Doe",
        delivery_owner="Alice Brown",
        rfe="",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="MaaS",
        issue_key="RHAISTRAT-1522",
        status="New",
        priority="Major",
        phase="GA",
        summary="GPU resource quota management",
        components="Serving",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Bob Wilson",
        delivery_owner="",
        rfe="RHAIRFE-457",
        labels="",
    ),
    FeatureRow(
        big_rock="MaaS",
        issue_key="RHAISTRAT-1523",
        status="In Progress",
        priority="Major",
        phase="EA1",
        summary="Model registry integration",
        components="Serving, Registry",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Jane Doe",
        delivery_owner="Carol Davis",
        rfe="",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="MaaS",
        issue_key="RHAISTRAT-1524",
        status="New",
        priority="Normal",
        phase="",
        summary="Custom runtime environment support",
        components="Serving",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Bob Wilson",
        delivery_owner="",
        rfe="",
        labels="",
    ),
    FeatureRow(
        big_rock="Gen AI Studio",
        issue_key="RHAISTRAT-1400",
        status="In Progress",
        priority="Critical",
        phase="EA1",
        summary="Prompt playground with model comparison",
        components="GenAI Studio",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Sarah Lee",
        delivery_owner="Dave Evans",
        rfe="RHAIRFE-500",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="Gen AI Studio",
        issue_key="RHAISTRAT-1401",
        status="Refinement",
        priority="Major",
        phase="EA2",
        summary="Agent workflow builder UI",
        components="GenAI Studio",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Sarah Lee",
        delivery_owner="Eve Foster",
        rfe="",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="Gen AI Studio",
        issue_key="RHAISTRAT-1402",
        status="New",
        priority="Major",
        phase="GA",
        summary="Template library for common AI tasks",
        components="GenAI Studio",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Sarah Lee",
        delivery_owner="",
        rfe="",
        labels="",
    ),
    FeatureRow(
        big_rock="Gen AI Studio",
        issue_key="RHAISTRAT-9004",
        status="In Progress",
        priority="Normal",
        phase="EA1",
        summary="RAG pipeline integration",
        components="GenAI Studio, Data",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Sarah Lee",
        delivery_owner="Frank Garcia",
        rfe="RHAIRFE-501",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="llm-d / xKS",
        issue_key="RHAISTRAT-1550",
        status="In Progress",
        priority="Critical",
        phase="EA1",
        summary="llm-d gateway for multi-model routing",
        components="Inference",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Mike Harris",
        delivery_owner="Grace Ito",
        rfe="",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="llm-d / xKS",
        issue_key="RHAISTRAT-1551",
        status="New",
        priority="Major",
        phase="EA2",
        summary="KServe autoscaler improvements",
        components="Inference, Platform",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Mike Harris",
        delivery_owner="",
        rfe="RHAIRFE-600",
        labels="",
    ),
    FeatureRow(
        big_rock="llm-d / xKS",
        issue_key="RHAISTRAT-1552",
        status="Refinement",
        priority="Normal",
        phase="",
        summary="Token-based load balancing",
        components="Inference",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Mike Harris",
        delivery_owner="Henry Jones",
        rfe="",
        labels="",
    ),
    FeatureRow(
        big_rock="Eval Hub",
        issue_key="RHAISTRAT-1600",
        status="In Progress",
        priority="Major",
        phase="EA1",
        summary="Model evaluation benchmarking suite",
        components="Evaluation",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Nancy Kim",
        delivery_owner="Iris Lee",
        rfe="RHAIRFE-700",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="Eval Hub",
        issue_key="RHAISTRAT-1601",
        status="New",
        priority="Normal",
        phase="EA2",
        summary="Custom evaluation metric framework",
        components="Evaluation",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Nancy Kim",
        delivery_owner="",
        rfe="",
        labels="",
    ),
    FeatureRow(
        big_rock="Eval Hub",
        issue_key="RHAISTRAT-1602",
        status="Refinement",
        priority="Major",
        phase="GA",
        summary="Automated regression testing for models",
        components="Evaluation, Data",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Nancy Kim",
        delivery_owner="Jack Ma",
        rfe="RHAIRFE-701",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAISTRAT-1700",
        status="In Progress",
        priority="Critical",
        phase="EA1",
        summary="MCP catalog and registry backend",
        components="Platform, Registry",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Oscar Park",
        delivery_owner="Karen Quinn",
        rfe="RHAIRFE-800",
        labels="3.5-candidate",
    ),
    FeatureRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAISTRAT-1701",
        status="Refinement",
        priority="Major",
        phase="EA2",
        summary="AI Hub unified search",
        components="Platform",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Oscar Park",
        delivery_owner="Larry Ross",
        rfe="",
        labels="",
    ),
    FeatureRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAISTRAT-1702",
        status="New",
        priority="Normal",
        phase="",
        summary="MCP tool discovery and versioning",
        components="Platform, Registry",
        target_release="rhoai-3.5",
        fix_version="",
        pm="Oscar Park",
        delivery_owner="",
        rfe="RHAIRFE-801",
        labels="",
    ),
    FeatureRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAISTRAT-1703",
        status="In Progress",
        priority="Major",
        phase="EA1",
        summary="Community model import pipeline",
        components="Platform",
        target_release="rhoai-3.5",
        fix_version="rhoai-3.5",
        pm="Oscar Park",
        delivery_owner="Mia Sanchez",
        rfe="",
        labels="3.5-candidate",
    ),
]

_SAMPLE_RFES: list[RfeRow] = [
    RfeRow(
        big_rock="MaaS",
        issue_key="RHAIRFE-456",
        status="Approved",
        priority="Major",
        summary="Multi-node inference for large models",
        components="Serving",
        pm="Jane Doe",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="MaaS",
        issue_key="RHAIRFE-457",
        status="New",
        priority="Major",
        summary="GPU quota management for multi-tenant environments",
        components="Serving, Platform",
        pm="Bob Wilson",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="Gen AI Studio",
        issue_key="RHAIRFE-500",
        status="Approved",
        priority="Critical",
        summary="Interactive prompt testing with model comparison",
        components="GenAI Studio",
        pm="Sarah Lee",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="llm-d / xKS",
        issue_key="RHAIRFE-600",
        status="Stakeholder Review",
        priority="Major",
        summary="KServe autoscaler for bursty inference workloads",
        components="Inference",
        pm="Mike Harris",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="Eval Hub",
        issue_key="RHAIRFE-700",
        status="Approved",
        priority="Major",
        summary="Standardized model evaluation benchmarks",
        components="Evaluation",
        pm="Nancy Kim",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="Eval Hub",
        issue_key="RHAIRFE-701",
        status="In Progress",
        priority="Normal",
        summary="Automated regression testing framework",
        components="Evaluation",
        pm="Nancy Kim",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAIRFE-800",
        status="Approved",
        priority="Critical",
        summary="MCP catalog backend with search and discovery",
        components="Platform",
        pm="Oscar Park",
        labels="3.5-candidate",
    ),
    RfeRow(
        big_rock="AI Hub incl MCP",
        issue_key="RHAIRFE-801",
        status="New",
        priority="Normal",
        summary="MCP tool versioning and lifecycle management",
        components="Platform, Registry",
        pm="Oscar Park",
        labels="3.5-candidate",
    ),
]


def get_sample_response(version: str = "3.5") -> CandidateResponse:
    """Return a sample CandidateResponse for demo mode.

    Args:
        version: Release version string.

    Returns:
        CandidateResponse with representative sample data.
    """
    features = _SAMPLE_FEATURES
    rfes = _SAMPLE_RFES
    big_rocks = _SAMPLE_BIG_ROCKS

    # Compute summary stats
    per_pillar: dict[str, PillarSummary] = {}
    per_rock: dict[str, PillarSummary] = {}
    rock_pillar_map = {r.name: r.pillar for r in big_rocks}

    for rock in big_rocks:
        rock_features = sum(1 for f in features if f.big_rock == rock.name)
        rock_rfes = sum(1 for r in rfes if r.big_rock == rock.name)
        per_rock[rock.name] = PillarSummary(features=rock_features, rfes=rock_rfes)

        pillar = rock.pillar
        if pillar in per_pillar:
            per_pillar[pillar] = PillarSummary(
                features=per_pillar[pillar].features + rock_features,
                rfes=per_pillar[pillar].rfes + rock_rfes,
            )
        else:
            per_pillar[pillar] = PillarSummary(features=rock_features, rfes=rock_rfes)

    rocks_with_data = sum(1 for r in big_rocks if per_rock.get(r.name, PillarSummary(features=0, rfes=0)).features > 0 or per_rock.get(r.name, PillarSummary(features=0, rfes=0)).rfes > 0)

    summary = SummaryStats(
        total_features=len(features),
        total_rfes=len(rfes),
        total_big_rocks=len(big_rocks),
        rocks_with_data=rocks_with_data,
        per_pillar=per_pillar,
        per_rock=per_rock,
    )

    # Build filter options
    all_statuses = sorted({f.status for f in features if f.status} | {r.status for r in rfes if r.status})
    all_teams = sorted({f.components for f in features if f.components})
    all_priorities = sorted({f.priority for f in features if f.priority} | {r.priority for r in rfes if r.priority})

    filter_options = FilterOptions(
        pillars=sorted({r.pillar for r in big_rocks if r.pillar}),
        rocks=[r.name for r in big_rocks],
        statuses=all_statuses,
        teams=all_teams,
        priorities=all_priorities,
    )

    return CandidateResponse(
        version=version,
        jira_base_url=JIRA_BROWSE_URL,
        last_refreshed=datetime.now(timezone.utc),
        demo_mode=True,
        summary=summary,
        big_rocks=big_rocks,
        features=features,
        rfes=rfes,
        filter_options=filter_options,
    )
